version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directories:
     - "/"
     - "/_examples/*"
    schedule:
      interval: "daily"
    groups:
      same-dependency:
        group-by: dependency-name
