version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: "gomod"
    directories:
     - "/"
     - "/_examples/*"
    schedule:
      interval: "daily"
    groups:
      same-dependency:
        group-by: dependency-name
